name: sp_alternative_env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - ca-certificates
  - libcxx
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
    - absl-py==2.1.0
    - agate==1.11.0
    - agate-dbf==0.2.3
    - agate-excel==0.4.1
    - agate-sql==0.7.2
    - aggdraw==1.3.19
    - anndata==0.10.8
    - anyio==4.4.0
    - appnope==0.1.4
    - APScheduler==3.10.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - array_api_compat==1.7.1
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==23.2.0
    - Babel==2.15.0
    - beautifulsoup4==4.12.3
    - bio==1.6.2
    - biopython==1.83
    - biothings-client==0.3.1
    - bleach==6.1.0
    - blinker==1.7.0
    - brotlipy==0.7.0
    - bx-python==0.11.0
    - cachetools==5.4.0
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.2
    - contourpy==1.2.0
    - csvkit==2.0.0
    - cycler==0.12.1
    - Cython==3.0.10
    - dbfread==2.0.7
    - debugpy==1.8.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - DendroPy==4.6.1
    - einops==0.6.1
    - et-xmlfile==1.1.0
    - ete3==3.1.3
    - exceptiongroup==1.2.2
    - executing==2.0.1
    - fastjsonschema==2.20.0
    - filelock==3.12.0
    - Flask==3.0.2
    - Flask-ReCaptcha==0.4.2
    - Flask-WTF==1.2.1
    - flatbuffers==24.3.25
    - fonttools==4.49.0
    - fqdn==1.5.1
    - fsspec==2024.6.1
    - gast==0.4.0
    - google-auth==2.32.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - google-recaptcha-flask==0.1.2
    - gprofiler-official==1.0.0
    - graphviz==0.20.3
    - greenlet==3.0.3
    - grpcio==1.66.1
    - h11==0.14.0
    - h5py==3.11.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.4
    - idna==3.6
    - ImmuneBuilder==0.0.9
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - ipykernel==6.29.5
    - ipython==8.26.0
    - ipywidgets==8.1.3
    - isodate==0.6.1
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jax==0.4.30
    - jaxlib==0.4.30
    - jedi==0.19.1
    - Jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.25
    - jsonpointer==2.1
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter_client==8.6.2
    - jupyter_core==5.7.2
    - jupyter_server==2.14.2
    - jupyter_server_terminals==0.5.3
    - jupyterlab==4.2.3
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.27.2
    - jupyterlab_widgets==3.0.11
    - jupyterthemes==0.20.0
    - keras==3.5.0
    - keras-tuner==1.4.7
    - kiwisolver==1.4.5
    - kt-legacy==1.0.5
    - leather==0.4.0
    - lesscpy==0.15.1
    - libclang==18.1.1
    - logomaker==0.8
    - Markdown==3.6
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.5
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.7
    - matplotlib-venn==0.11.9
    - mdurl==0.1.2
    - mistune==3.0.2
    - ml-dtypes==0.3.2
    - mpld3==0.5.10
    - mpmath==1.3.0
    - msasim==24.9.1
    - mygene==3.2.2
    - namex==0.0.8
    - natsort==8.4.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - notebook==7.2.1
    - notebook_shim==0.2.4
    - numpy==1.23.5
    - oauthlib==3.2.2
    - olefile==0.47
    - openmm==0.2
    - openpyxl==3.1.3
    - opt-einsum==3.3.0
    - optree==0.12.1
    - overrides==7.7.0
    - packaging==23.2
    - pandas==2.2.0
    - pandocfilters==1.5.1
    - parsedatetime==2.6
    - parso==0.8.4
    - pdbfixer==1.9.0
    - pexpect==4.9.0
    - pillow==10.2.0
    - platformdirs==4.2.0
    - ply==3.11
    - pooch==1.8.0
    - prometheus_client==0.20.0
    - prompt_toolkit==3.0.47
    - protobuf==4.25.4
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==17.0.0
    - pyasn1==0.6.0
    - pyasn1_modules==0.4.0
    - pyBigWig==0.3.22
    - pydeseq2==0.4.10
    - pydot==3.0.1
    - Pygments==2.18.0
    - pyparsing==3.1.1
    - pysam==0.22.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-slugify==8.0.4
    - pytimeparse==1.1.8
    - pytz==2024.1
    - PyYAML==6.0.1
    - pyzmq==26.0.3
    - qtconsole==5.5.2
    - QtPy==2.4.1
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - robinson-foulds==1.2
    - rpds-py==0.19.0
    - rsa==4.9
    - RSeQC==5.0.3
    - safetensors==0.4.3
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - seaborn==0.13.2
    - Send2Trash==1.8.3
    - sniffio==1.3.1
    - soupsieve==2.5
    - SQLAlchemy==2.0.30
    - stack-data==0.6.3
    - storable==1.2.4
    - style==1.1.0
    - sympy==1.12
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.16.2
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.4.0
    - terminado==0.18.1
    - text-unidecode==1.3
    - tf-explain==0.3.1
    - tf_keras==2.16.0
    - threadpoolctl==3.3.0
    - tinycss2==1.3.0
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torch==2.0.1
    - tornado==6.4.1
    - tqdm==4.66.1
    - traitlets==5.14.3
    - transformers==4.42.4
    - types-python-dateutil==2.9.0.20240316
    - typing_extensions==4.12.2
    - tzdata==2023.4
    - tzlocal==5.2
    - update==0.0.1
    - uri-template==1.3.0
    - urllib3==2.2.0
    - visualkeras==0.1.3
    - voila==0.5.7
    - wcwidth==0.2.13
    - webcolors==24.6.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - websockets==12.0
    - Werkzeug==3.0.1
    - widgetsnbextension==4.0.11
    - wrapt==1.14.1
    - WTForms==3.1.2
    - xlrd==2.0.1
    - zipp==3.17.0
