name: msa_dl_model_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhcf101f3_2
  - fonttools=4.61.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - icu=78.2=h38cb7af_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310h563d721_2
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.2=h8088a28_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.54=h132b30e_0
  - libsqlite=3.51.2=h1ae2325_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - matplotlib=3.10.8=py310hb6292c7_0
  - matplotlib-base=3.10.8=py310h0181960_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - numpy=1.26.4=py310hd45542a_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pillow=12.1.0=py310hc037f36_0
  - pip=25.3=pyh8b19718_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyparsing=3.3.1=pyhcf101f3_0
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h46df422_0
  - scipy=1.15.2=py310h32ab4ed_0
  - six=1.17.0=pyhe01879c_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.4=py310hfe3a0ae_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - flatbuffers==25.12.19
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==3.5.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.1.0
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - protobuf==4.25.8
      - pygments==2.19.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.5.1
      - setuptools==80.9.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.3.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - wrapt==2.0.1

